// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// RelatedTopicsView represents a row from 'public.related_topics_view'.
type RelatedTopicsView struct {
	TopicID        sql.NullInt64  `json:"topic_id"`         // topic_id
	RelatedTopicID sql.NullInt64  `json:"related_topic_id"` // related_topic_id
	CategoryID     sql.NullInt64  `json:"category_id"`      // category_id
	Title          sql.NullString `json:"title"`            // title
	Description    sql.NullString `json:"description"`      // description
	CreatedBy      sql.NullInt64  `json:"created_by"`       // created_by
	UpdatedBy      sql.NullInt64  `json:"updated_by"`       // updated_by
}
