// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// TagTopicsView represents a row from 'public.tag_topics_view'.
type TagTopicsView struct {
	TagID       sql.NullInt64  `json:"tag_id"`      // tag_id
	TopicID     sql.NullInt64  `json:"topic_id"`    // topic_id
	CategoryID  sql.NullInt64  `json:"category_id"` // category_id
	Title       sql.NullString `json:"title"`       // title
	Description sql.NullString `json:"description"` // description
	CreatedBy   sql.NullInt64  `json:"created_by"`  // created_by
	UpdatedBy   sql.NullInt64  `json:"updated_by"`  // updated_by
}
